version: '3.8'

services:
  backend:
    build: ./backend
    container_name: strm-generator-backend
    ports:
      - "3011:3011"
    volumes:
      - /data/clouddrive/gdrive:/data/clouddrive/gdrive:ro
      - /opt/strm_yesy/output:/app/output
      - strm-data:/app/data
    environment:
      - STRM_SOURCE_DIR=/data/clouddrive/gdrive
      - STRM_OUTPUT_DIR=/app/output
      - STRM_BASE_DIR=/app/data
      - STRS_AUTH_USER=jdyyds
      - STRS_AUTH_PASS=f15015699065
      - EMBY_URL=http://188.165.244.137:8096
      - EMBY_API_KEY=c697ac73dabb4e94aa0ac447409f7569
      - EMBY_RECENT_DAYS=7
    restart: unless-stopped
    networks:
      - strm-net

  frontend:
    build: ./frontend
    container_name: strm-generator-frontend
    ports:
      - "8888:80"
    restart: unless-stopped
    networks:
      - strm-net
    depends_on:
      - backend

networks:
  strm-net:
    driver: bridge

volumes:
  strm-data:
